/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppRmsRouteImport } from './routes/_app.rms'
import { Route as AppHistoryRouteImport } from './routes/_app.history'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppProgramsIndexRouteImport } from './routes/_app.programs.index'
import { Route as AppWorkoutsImportRouteImport } from './routes/_app.workouts.import'
import { Route as AppWorkoutsDateRouteImport } from './routes/_app.workouts.$date'
import { Route as AppProgramsNewRouteImport } from './routes/_app.programs.new'
import { Route as AppProgramsIdRouteImport } from './routes/_app.programs.$id'
import { Route as AppHelpInputFormatRouteImport } from './routes/_app.help.input-format'
import { Route as AppProgramsIdProgressionRouteImport } from './routes/_app.programs.$id_.progression'
import { Route as AppProgramsIdEditRouteImport } from './routes/_app.programs.$id_.edit'
import { Route as AppProgramsIdAssignRouteImport } from './routes/_app.programs.$id_.assign'
import { Route as AppExercisesIdProgressionRouteImport } from './routes/_app.exercises.$id.progression'
import { Route as AppExercisesIdEditRouteImport } from './routes/_app.exercises.$id.edit'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRmsRoute = AppRmsRouteImport.update({
  id: '/rms',
  path: '/rms',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsIndexRoute = AppProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsImportRoute = AppWorkoutsImportRouteImport.update({
  id: '/workouts/import',
  path: '/workouts/import',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsDateRoute = AppWorkoutsDateRouteImport.update({
  id: '/workouts/$date',
  path: '/workouts/$date',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsNewRoute = AppProgramsNewRouteImport.update({
  id: '/programs/new',
  path: '/programs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsIdRoute = AppProgramsIdRouteImport.update({
  id: '/programs/$id',
  path: '/programs/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpInputFormatRoute = AppHelpInputFormatRouteImport.update({
  id: '/help/input-format',
  path: '/help/input-format',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsIdProgressionRoute =
  AppProgramsIdProgressionRouteImport.update({
    id: '/programs/$id_/progression',
    path: '/programs/$id/progression',
    getParentRoute: () => AppRoute,
  } as any)
const AppProgramsIdEditRoute = AppProgramsIdEditRouteImport.update({
  id: '/programs/$id_/edit',
  path: '/programs/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsIdAssignRoute = AppProgramsIdAssignRouteImport.update({
  id: '/programs/$id_/assign',
  path: '/programs/$id/assign',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesIdProgressionRoute =
  AppExercisesIdProgressionRouteImport.update({
    id: '/exercises/$id/progression',
    path: '/exercises/$id/progression',
    getParentRoute: () => AppRoute,
  } as any)
const AppExercisesIdEditRoute = AppExercisesIdEditRouteImport.update({
  id: '/exercises/$id/edit',
  path: '/exercises/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/coach': typeof AppCoachRoute
  '/history': typeof AppHistoryRoute
  '/rms': typeof AppRmsRoute
  '/settings': typeof AppSettingsRoute
  '/help/input-format': typeof AppHelpInputFormatRoute
  '/programs/$id': typeof AppProgramsIdRoute
  '/programs/new': typeof AppProgramsNewRoute
  '/workouts/$date': typeof AppWorkoutsDateRoute
  '/workouts/import': typeof AppWorkoutsImportRoute
  '/programs/': typeof AppProgramsIndexRoute
  '/exercises/$id/edit': typeof AppExercisesIdEditRoute
  '/exercises/$id/progression': typeof AppExercisesIdProgressionRoute
  '/programs/$id/assign': typeof AppProgramsIdAssignRoute
  '/programs/$id/edit': typeof AppProgramsIdEditRoute
  '/programs/$id/progression': typeof AppProgramsIdProgressionRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/coach': typeof AppCoachRoute
  '/history': typeof AppHistoryRoute
  '/rms': typeof AppRmsRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/help/input-format': typeof AppHelpInputFormatRoute
  '/programs/$id': typeof AppProgramsIdRoute
  '/programs/new': typeof AppProgramsNewRoute
  '/workouts/$date': typeof AppWorkoutsDateRoute
  '/workouts/import': typeof AppWorkoutsImportRoute
  '/programs': typeof AppProgramsIndexRoute
  '/exercises/$id/edit': typeof AppExercisesIdEditRoute
  '/exercises/$id/progression': typeof AppExercisesIdProgressionRoute
  '/programs/$id/assign': typeof AppProgramsIdAssignRoute
  '/programs/$id/edit': typeof AppProgramsIdEditRoute
  '/programs/$id/progression': typeof AppProgramsIdProgressionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/history': typeof AppHistoryRoute
  '/_app/rms': typeof AppRmsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/help/input-format': typeof AppHelpInputFormatRoute
  '/_app/programs/$id': typeof AppProgramsIdRoute
  '/_app/programs/new': typeof AppProgramsNewRoute
  '/_app/workouts/$date': typeof AppWorkoutsDateRoute
  '/_app/workouts/import': typeof AppWorkoutsImportRoute
  '/_app/programs/': typeof AppProgramsIndexRoute
  '/_app/exercises/$id/edit': typeof AppExercisesIdEditRoute
  '/_app/exercises/$id/progression': typeof AppExercisesIdProgressionRoute
  '/_app/programs/$id_/assign': typeof AppProgramsIdAssignRoute
  '/_app/programs/$id_/edit': typeof AppProgramsIdEditRoute
  '/_app/programs/$id_/progression': typeof AppProgramsIdProgressionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/coach'
    | '/history'
    | '/rms'
    | '/settings'
    | '/help/input-format'
    | '/programs/$id'
    | '/programs/new'
    | '/workouts/$date'
    | '/workouts/import'
    | '/programs/'
    | '/exercises/$id/edit'
    | '/exercises/$id/progression'
    | '/programs/$id/assign'
    | '/programs/$id/edit'
    | '/programs/$id/progression'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-up'
    | '/coach'
    | '/history'
    | '/rms'
    | '/settings'
    | '/'
    | '/help/input-format'
    | '/programs/$id'
    | '/programs/new'
    | '/workouts/$date'
    | '/workouts/import'
    | '/programs'
    | '/exercises/$id/edit'
    | '/exercises/$id/progression'
    | '/programs/$id/assign'
    | '/programs/$id/edit'
    | '/programs/$id/progression'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/sign-up'
    | '/_app/coach'
    | '/_app/history'
    | '/_app/rms'
    | '/_app/settings'
    | '/_app/'
    | '/_app/help/input-format'
    | '/_app/programs/$id'
    | '/_app/programs/new'
    | '/_app/workouts/$date'
    | '/_app/workouts/import'
    | '/_app/programs/'
    | '/_app/exercises/$id/edit'
    | '/_app/exercises/$id/progression'
    | '/_app/programs/$id_/assign'
    | '/_app/programs/$id_/edit'
    | '/_app/programs/$id_/progression'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rms': {
      id: '/_app/rms'
      path: '/rms'
      fullPath: '/rms'
      preLoaderRoute: typeof AppRmsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/': {
      id: '/_app/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof AppProgramsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/import': {
      id: '/_app/workouts/import'
      path: '/workouts/import'
      fullPath: '/workouts/import'
      preLoaderRoute: typeof AppWorkoutsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workouts/$date': {
      id: '/_app/workouts/$date'
      path: '/workouts/$date'
      fullPath: '/workouts/$date'
      preLoaderRoute: typeof AppWorkoutsDateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/new': {
      id: '/_app/programs/new'
      path: '/programs/new'
      fullPath: '/programs/new'
      preLoaderRoute: typeof AppProgramsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/$id': {
      id: '/_app/programs/$id'
      path: '/programs/$id'
      fullPath: '/programs/$id'
      preLoaderRoute: typeof AppProgramsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help/input-format': {
      id: '/_app/help/input-format'
      path: '/help/input-format'
      fullPath: '/help/input-format'
      preLoaderRoute: typeof AppHelpInputFormatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/$id_/progression': {
      id: '/_app/programs/$id_/progression'
      path: '/programs/$id/progression'
      fullPath: '/programs/$id/progression'
      preLoaderRoute: typeof AppProgramsIdProgressionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/$id_/edit': {
      id: '/_app/programs/$id_/edit'
      path: '/programs/$id/edit'
      fullPath: '/programs/$id/edit'
      preLoaderRoute: typeof AppProgramsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/$id_/assign': {
      id: '/_app/programs/$id_/assign'
      path: '/programs/$id/assign'
      fullPath: '/programs/$id/assign'
      preLoaderRoute: typeof AppProgramsIdAssignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/$id/progression': {
      id: '/_app/exercises/$id/progression'
      path: '/exercises/$id/progression'
      fullPath: '/exercises/$id/progression'
      preLoaderRoute: typeof AppExercisesIdProgressionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises/$id/edit': {
      id: '/_app/exercises/$id/edit'
      path: '/exercises/$id/edit'
      fullPath: '/exercises/$id/edit'
      preLoaderRoute: typeof AppExercisesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppRmsRoute: typeof AppRmsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppHelpInputFormatRoute: typeof AppHelpInputFormatRoute
  AppProgramsIdRoute: typeof AppProgramsIdRoute
  AppProgramsNewRoute: typeof AppProgramsNewRoute
  AppWorkoutsDateRoute: typeof AppWorkoutsDateRoute
  AppWorkoutsImportRoute: typeof AppWorkoutsImportRoute
  AppProgramsIndexRoute: typeof AppProgramsIndexRoute
  AppExercisesIdEditRoute: typeof AppExercisesIdEditRoute
  AppExercisesIdProgressionRoute: typeof AppExercisesIdProgressionRoute
  AppProgramsIdAssignRoute: typeof AppProgramsIdAssignRoute
  AppProgramsIdEditRoute: typeof AppProgramsIdEditRoute
  AppProgramsIdProgressionRoute: typeof AppProgramsIdProgressionRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppRmsRoute: AppRmsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppHelpInputFormatRoute: AppHelpInputFormatRoute,
  AppProgramsIdRoute: AppProgramsIdRoute,
  AppProgramsNewRoute: AppProgramsNewRoute,
  AppWorkoutsDateRoute: AppWorkoutsDateRoute,
  AppWorkoutsImportRoute: AppWorkoutsImportRoute,
  AppProgramsIndexRoute: AppProgramsIndexRoute,
  AppExercisesIdEditRoute: AppExercisesIdEditRoute,
  AppExercisesIdProgressionRoute: AppExercisesIdProgressionRoute,
  AppProgramsIdAssignRoute: AppProgramsIdAssignRoute,
  AppProgramsIdEditRoute: AppProgramsIdEditRoute,
  AppProgramsIdProgressionRoute: AppProgramsIdProgressionRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
