import "./global.css";
import { Georama } from "next/font/google";

const georama = Georama({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={georama.className}>{children}</body>
    </html>
  );
}
