import "./global.css";
import { Georama } from "next/font/google";
import styles from "./layout.module.scss";
import Header from "./components/Header";

const georama = Georama({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={georama.className}>
        <div className={styles.root}>
          {/* @ts-expect-error Server Component */}
          <Header />
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
