import "../global.css";
import { Georama } from "next/font/google";
import styles from "./layout.module.scss";

const georama = Georama({
  subsets: ["latin"],
});

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={georama.className}>
        <div className={styles.root}>{children}</div>
      </body>
    </html>
  );
}
