name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      start-date: ${{ steps.start-date.outputs.date }}
      end-date: ${{ steps.end-date.outputs.date }}
    steps:
      - id: start-date
        run: echo "date=$(date +"%d" --date="1 week ago")" >> "$GITHUB_OUTPUT"

      - id: end-date
        run: echo "date=$(date +" %d.%m.%Y"  --date="1 day ago")" >> "$GITHUB_OUTPUT"

      - uses: imjohnbo/extract-issue-template-fields@v1
        id: extract
        with:
          path: .github/ISSUE_TEMPLATE/custom.md

      - uses: imjohnbo/issue-bot@v3
        with:
          labels: ${{ steps.extract.outputs.labels }}
          title: "${{ steps.start-date.outputs.date }}. - ${{ steps.end-date.outputs.date}}"
          body: ${{ steps.extract.outputs.body }}
          token: ${{ secrets.GH_TOKEN }}
          project-v2-path: "users/jarlerik/projects/1"
