name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  read-template:
    runs-on: ubuntu-latest
    steps:
      - run: |
          input="../.github/ISSUE_TEMPLATE/custom.md"
          while IFS= read -r line
          do
              content=$line
              echo "$line"
              echo ::set-output name=issue_content::$content
          done < "$input"
      # test to see if done correctly - should echo "value"
      - run: echo "${​​​​{​​​​​​​​ steps.output_test.outputs.template_text }​​​​​​​​​​​}​​​​​​​​​​​​​​​"
      - run: gh issue create --title "Created issue from file template" -F "../.github/ISSUE_TEMPLATE/custom.md​​​​​​​​​​​​​"
